### ISSUE TITLE
New check: CFF Table ASCII Strings

### ISSUE THREAD

**Issue by kaydeearts** [miguelsousa/openbakery#128]
## What needs to be checked?

The CFF table fields need to be checked to ensure all strings are in ASCII.

## Detailed description of the problem 

We found that a font with an è in the fullname field of the CFF top dict was causing crashes within fontTools when it was being saved.

## Resources and steps needed to reproduce the problem

Will update this issue with a test case soon, and add it to the PR.

## Suggested profile

Suggest which profile the check should be added to. The most common are:

- [ ] Vendor-specific: Google Fonts
- [x] Vendor-specific: Adobe Fonts
- [ ] OpenType (requirements imposed by the OpenType specification)
- [ ] Universal (broadly accepted best practices on the type design community)
- [ ] Other:

## Suggested result

Which log result level should the check have:

- [x] 🔥 **FAIL** (An issue that must be corrected for the font to function properly)
- [ ] ⚠️ **WARN** (A potential issues that may need to be addressed)

## Severity assessment

(Classify the problem on a scale of 1 (minor) to 5 (major). How "buggy" would the font be considered if it had the problem described?)
4

**Comment by loris-maru** [comment]
Hello,

I have a check "fail" for the adobe one when entering Hangeul characters (korean script) in the Localized Family Names.
I get the message that it doesn't fit into the ASCII script.

Would you have any idea how to setup correctly this specific parameter for a Hangeul typeface please?

**Comment by miguelsousa** [comment]
@loris-maru to be able to guide you please provide the following:
1. The exact error you're getting
2. A **ttx** dump of the font's `name` table; to get the XML dump run the following command: `ttx -t name your_font.otf`
